//! Native Linux execution. Exported units run independently of the K3 Up agent.
use crate::model::{
    Kind, Manifest, Missed, PathStyle, Restart, RestartLimit, ScheduleAction, Workload,
};
use anyhow::{Result, bail};
use std::{collections::BTreeMap, path::Path};

pub(crate) fn quoted(value: &str) -> String {
    format!(
        "\"{}\"",
        value
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('%', "%%")
            .replace('$', "$$")
    )
}
fn literal(value: &str) -> String {
    // Non-ExecStart directives do not expand shell-style dollar variables.
    quoted(value).replace("$$", "$")
}

pub fn render(manifest: &Manifest) -> Result<BTreeMap<String, String>> {
    manifest.validate_for(PathStyle::Unix)?;
    let mut units = BTreeMap::new();
    for workload in &manifest.workloads {
        if workload.working_directory.contains('\\')
            || workload.working_directory.trim_end() != workload.working_directory
        {
            bail!(
                "Native systemd export cannot preserve backslashes or trailing whitespace in working directories"
            );
        }
        for key in workload.environment.keys() {
            if !key
                .bytes()
                .enumerate()
                .all(|(i, b)| b == b'_' || b.is_ascii_alphabetic() || (i > 0 && b.is_ascii_digit()))
            {
                bail!("Native systemd environment names must be ASCII identifiers: {key}");
            }
        }
        if workload.readiness_tcp.is_some() {
            bail!(
                "Native export of '{}' cannot preserve TCP readiness yet; use an application with native systemd readiness or omit the check",
                workload.name
            );
        }
        let mut unit = format!(
            "# Generated by K3 Up.\n[Unit]\nDescription=K3 Up {}\n",
            workload.name
        );
        if !workload.depends_on.is_empty() {
            let deps = workload
                .depends_on
                .iter()
                .map(|name| format!("k3up-{name}.service"))
                .collect::<Vec<_>>()
                .join(" ");
            unit.push_str(&format!("Requires={deps}\nAfter={deps}\n"));
        }
        unit.push_str(&start_limit(workload));
        unit.push_str(&format!(
            "\n[Service]\nType={}\nWorkingDirectory={}\nExecStart={}\n",
            if workload.kind == Kind::Job {
                "oneshot"
            } else {
                "exec"
            },
            workload.working_directory.replace('%', "%%"),
            std::iter::once(workload.executable.as_str())
                .chain(workload.args.iter().map(String::as_str))
                .map(quoted)
                .collect::<Vec<_>>()
                .join(" ")
        ));
        for (key, value) in &workload.environment {
            unit.push_str(&format!(
                "Environment={}\n",
                literal(&format!("{key}={value}"))
            ));
        }
        let restart = if workload.kind == Kind::Job {
            "no"
        } else {
            match workload.restart {
                Restart::Never => "no",
                Restart::OnFailure => "on-failure",
                Restart::Always => "always",
            }
        };
        unit.push_str(&format!("Restart={restart}\nRestartSec={}\nTimeoutStopSec={}\nKillMode=control-group\nStandardOutput=journal\nStandardError=journal\n",
            workload.restart_delay_secs, workload.stop_timeout_secs));
        if !workload.success_exit_codes.is_empty() {
            let codes = workload
                .success_exit_codes
                .iter()
                .map(i32::to_string)
                .collect::<Vec<_>>()
                .join(" ");
            unit.push_str(&format!("SuccessExitStatus={codes}\n"));
        }
        if let Some(timeout) = workload.run_timeout_secs {
            unit.push_str(&format!(
                "{}={timeout}\n",
                if workload.kind == Kind::Job {
                    "TimeoutStartSec"
                } else {
                    "RuntimeMaxSec"
                }
            ));
        } else if workload.kind == Kind::Job {
            unit.push_str("TimeoutStartSec=infinity\n");
        }
        unit.push_str("\n[Install]\nWantedBy=default.target\n");
        units.insert(format!("k3up-{}.service", workload.name), unit);
        if let Some(schedule) = &workload.schedule {
            let Some(seconds) = schedule.every_secs else {
                bail!(
                    "Native systemd export currently supports every_secs schedules only; cron is supported by the local agent"
                );
            };
            if schedule.action == ScheduleAction::Restart {
                bail!("Native export currently supports scheduled starts only");
            }
            if schedule.missed == Missed::RunOnce {
                bail!(
                    "Native interval timers cannot preserve run_once catch-up; use missed = 'skip'"
                );
            }
            units.insert(format!("k3up-{}.timer", workload.name), format!("# Generated by K3 Up.\n[Unit]\nDescription=Schedule for {}\n\n[Timer]\nOnActiveSec={seconds}s\nOnUnitActiveSec={seconds}s\nAccuracySec=1s\nUnit=k3up-{}.service\n\n[Install]\nWantedBy=timers.target\n", workload.name, workload.name));
        }
    }
    Ok(units)
}

/// Jobs and unlimited services are never rate limited; RestartSec= alone paces their retries.
fn start_limit(workload: &Workload) -> String {
    match workload.max_restarts {
        RestartLimit::Count(limit) if workload.kind == Kind::Service => {
            format!("StartLimitIntervalSec=300\nStartLimitBurst={}\n", limit + 1)
        }
        _ => "StartLimitIntervalSec=0\n".to_string(),
    }
}

pub fn export(manifest: &Manifest, directory: &Path) -> Result<usize> {
    let units = render(manifest)?;
    std::fs::create_dir_all(directory)?;
    for (name, text) in &units {
        std::fs::write(directory.join(name), text)?;
    }
    Ok(units.len())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Workload;
    #[test]
    fn escapes_systemd_expansion_and_argument_boundaries() {
        let workload = Workload {
            name: "test".into(),
            executable: "/bin/echo".into(),
            working_directory: "/tmp".into(),
            args: vec!["a b".into(), "$HOME %n".into()],
            ..Default::default()
        };
        let units = render(&Manifest {
            version: 1,
            workloads: vec![workload],
        })
        .unwrap();
        assert!(
            units["k3up-test.service"].contains("ExecStart=\"/bin/echo\" \"a b\" \"$$HOME %%n\"")
        );
    }
    #[test]
    fn directory_paths_are_not_shell_quoted_and_jobs_are_not_rate_limited() {
        let workload = Workload {
            name: "job".into(),
            executable: "/bin/echo".into(),
            working_directory: "/tmp/a directory%".into(),
            kind: Kind::Job,
            ..Default::default()
        };
        let units = render(&Manifest {
            version: 1,
            workloads: vec![workload],
        })
        .unwrap();
        let unit = &units["k3up-job.service"];
        assert!(unit.contains("WorkingDirectory=/tmp/a directory%%\n"));
        assert!(unit.contains("StartLimitIntervalSec=0\n"));
        assert!(!unit.contains("StartLimitBurst"));
        assert!(unit.contains("TimeoutStartSec=infinity\n"));
    }
    #[test]
    fn maps_restart_limits_backoff_and_success_codes() {
        let counted = Workload {
            name: "counted".into(),
            executable: "/bin/echo".into(),
            working_directory: "/tmp".into(),
            max_restarts: RestartLimit::Count(3),
            ..Default::default()
        };
        let unlimited = Workload {
            name: "sentinel".into(),
            executable: "/bin/echo".into(),
            working_directory: "/tmp".into(),
            restart: Restart::Always,
            max_restarts: RestartLimit::Unlimited,
            restart_backoff: crate::model::RestartBackoff::Fixed,
            restart_delay_secs: 5,
            success_exit_codes: vec![3, 75],
            ..Default::default()
        };
        let units = render(&Manifest {
            version: 1,
            workloads: vec![counted, unlimited],
        })
        .unwrap();
        let counted = &units["k3up-counted.service"];
        assert!(counted.contains("StartLimitIntervalSec=300\nStartLimitBurst=4\n"));
        assert!(!counted.contains("SuccessExitStatus"));
        let sentinel = &units["k3up-sentinel.service"];
        assert!(sentinel.contains("StartLimitIntervalSec=0\n"));
        assert!(!sentinel.contains("StartLimitBurst"));
        assert!(sentinel.contains("Restart=always\nRestartSec=5\n"));
        assert!(sentinel.contains("SuccessExitStatus=3 75\n"));
    }
}
